name: Deploy
on: [push]
jobs:
        build:
                runs-on: ubuntu-latest
                steps:
                        - uses: actions/checkout@v1
                        - name: Copy repository contents via scp
                          uses: appleboy/scp-action@master
                          env:
                                  HOST: ${{ secrets.HOST }}
                                  USERNAME: ${{ secrets.USERNAME }}
                                  PORT: ${{ secrets.PORT }}
                                  KEY: ${{ secrets.SSHKEYS }}
                          with:
                                  source: "."
                                  target: "/var/www/alewebdev.com"
                        - name: 'install Nodejs'
                          uses: actions/setup-node@v1
                          with:
                                node-version: '12.x'
                        - name: installing dependencies
                          run: npm install
                        - name: building 
                          run: npm run build
