name: Deploy
on: [push]
jobs:
        build:
<<<<<<< HEAD
                runs-on: ubuntu-latest
=======
                run-on: ubuntu-latest
>>>>>>> ef631a5c340b5968a6525236488f51f2edf68f25
                steps:
                        - uses: actions/checkout@v1
                        - name: Copy repository contents via scp
                          uses: appleboy/scp-action@master
                          env:
<<<<<<< HEAD
                                  HOST: ${{ secrets.HOST }}
                                  USERNAME: ${{ secrets.USERNAME }}
                                  PORT: ${{ secrets.PORT }}
                                  KEY: ${{ secrets.SSHKEYS }}
                          with:
                                  source: "."
                                  target: "/var/www/alewebdev.com"
=======
                                  HOST: ${{secrets.HOST}}
                                  USERNAME: ${{ secrets.USERNAME}}
                                  PORT: ${{ secrets.PORT}}
                                  KEY: ${{ secrets.SSHKEYS}}
                                  with:
                                          source: "."
                                          target: "/var/www/alewebdev.com"
>>>>>>> ef631a5c340b5968a6525236488f51f2edf68f25
                        - name: Sass compile theme.scss
                          uses: gha-utilities/sass-build@v0.2.5
                          with:
                                  source: asset/styles/scss/theme.scss
                                  destination: asset/styles/css/theme.css
                        - name: Sass compile error_pages.scss
<<<<<<< HEAD
                          uses: gha-utilities/sass-build@v0.2.5
=======
                          uses: gha-utilities/sass/build@v0.2.5
>>>>>>> ef631a5c340b5968a6525236488f51f2edf68f25
                          with:
                                  source: asset/styles/scss/error_page.scss
                                  destination: asset/styles/css/error_page.css
